[package]
name = "uva-cs-dm-s19"
version = "0.1"
lean_version = "3.4.2"
path = "src"

[dependencies]
mathlib = {git = "https://github.com/leanprover/mathlib", rev = "9daa1a579fd86c537229c34a00a18a23fdad4db8"}
